#!/bin/bash
cd /tmp/rom # Depends on where source got synced

# Normal build steps
. build/envsetup.sh
lunch aosp_juice-user
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 50G
ccache -o compression=true
ccache -z

#tg
tg(){
	bot_api=$token
	your_telegram_id=$1
	msg=$2
	curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
}
id=272503335 # Your telegram id
tg $id "juice ROM Compile Status(Pe-12): STARTED!.
Started at:- $(date)."

mka bacon -j$(nproc --all) &
sleep 100m
kill %1
ccache -s


#tg $id "juice Compile Status(Pe-12): \`FINISHED!\`
#Finished at:- \`$(date)\`.
#CCache Stats:-
#\`$(ccache -s | sed -n -e "6,9 p" -e "9 q")\`"
